### ISSUE TITLE
Contact form shortcode, widget or page?

### ISSUE THREAD

**Issue by Rubonnek** [hbstack/theme#137]
It would be nice to have a built-in contact form that could be enabled somehow. Perhaps one under the author page is enough.

I can't seem to find it if there is any.

**Comment by razonyang** [comment]
Not implemented yet, will create a module for this, no ETA guarantee.

**Comment by Rubonnek** [comment]
If it helps, a self-hosted alternative I use is [formailer](https://github.com/torrayne/formailer).

**Comment by razonyang** [comment]
FYI @Rubonnek, there is a bug of the form validations (error messages not showing) on production env, fixed since `github.com/hbstack/form` `v0.1.1`, it may affect the Staticman comments and contact modules.

```sh
hugo mod get -u github.com/hbstack/form@v0.1.1
```

The fixed contact form as below.

![image](https://github.com/hbstack/theme/assets/17720932/07c96fc5-1c9a-4bb5-834d-39b087eae9c5)

**Comment by Rubonnek** [comment]
Thanks for letting me know!
